### PR TITLE
Feat: vela up support read from stdin && refine CLI output && fix vela addon command

### PR DESCRIPTION
**Pull request by wonderflow**
Signed-off-by: Jianbo Sun <jianbo.sjb@alibaba-inc.com>

### Description of your changes

image

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/oam-dev/kubevela/blob/master/contribute/create-pull-request.md).
- [x] [Related Docs](https://github.com/oam-dev/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Review by barnettZQG — APPROVED** [review]

**Comment by zzxwill** [comment]
Pasting or writing a Yaml, especially with `EOF` in the command line is difficult. Any background for this feature?

**Comment by wonderflow** [comment]
> Pasting or writing a Yaml, especially with `EOF` in the command line is difficult. Any background for this feature?

you can see the picture in the PR description.

**Comment by zzxwill** [comment]
> > Pasting or writing a Yaml, especially with `EOF` in the command line is difficult. Any background for this feature?
> 
> you can see the picture in the PR description, it's also a feature of K8s. Unix style pipe, for example:
> 
> ```
> cat vela.yaml | vela up -f -
> ```

It's friendly to `cat` a file. Do users have to paste a YAML as in the picture?

**Comment by wonderflow** [comment]
> > > Pasting or writing a Yaml, especially with `EOF` in the command line is difficult. Any background for this feature?
> > 
> > 
> > you can see the picture in the PR description, it's also a feature of K8s. Unix style pipe, for example:
> > ```
> > cat vela.yaml | vela up -f -
> > ```
> 
> It's friendly to `cat` a file. Do users have to paste a YAML as in the picture?

Our docs use in this way, this can be easily copy paste.

**Review by zzxwill — APPROVED** [review]

**Review by hongchaodeng — APPROVED** [review]

**Pull request merged**
