### PR TITLE
Support remote git repo for Terraform configuration

### PR DESCRIPTION
**Pull request by zzxwill**
Besides inline HCL Configuration, supprted remote git repo Configuration

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by hongchaodeng — APPROVED** [review]
lgtm

**Comment by leejanee** [comment]
Does it support specifying directory in the remote git repo?

**Review by wonderflow — APPROVED** [review]
please fix the conflict

**Comment by zzxwill** [comment]
> Does it support specifying directory in the remote git repo?

Currently no. Planning to support this feature, besides with private git repo, in a later release.

**Review by leejanee — APPROVED** [review]

**Pull request merged**
