### PR TITLE
Chore: Nominate @devholic as as a Review member

### PR DESCRIPTION
**Pull request by wonderflow**
Signed-off-by: Jianbo Sun <jianbo.sjb@alibaba-inc.com>

### Description of your changes

@devholic has contribute several PRs https://github.com/oam-dev/kubevela/pulls?q=is%3Apr+author%3Adevholic+is%3Aclosed 

Including some core features like https://github.com/oam-dev/kubevela/pull/3434 

As talked with @devholic , he's also going to contribute more to the community, so I nominate him as a review member.

Ping @barnettZQG @leejanee and other maintainers, please LGTM or approve if you agree!

### CODE REVIEW

**Review by zzxwill — APPROVED** [review]
LGTM！

**Comment by devholic** [comment]
Thanks for the nomination! 🙏

**Review by Somefive — APPROVED** [review]
LGTM

**Comment by BinaryHB0916** [comment]
LGTM

**Review by BinaryHB0916 — APPROVED** [review]

**Review by FogDong — APPROVED** [review]
LGTM, thanks for the contributions! 🎉

**Review by barnettZQG — APPROVED** [review]
@devholic Looking forward to your more viewpoint.

**Pull request merged**
