### PR TITLE
Support patch data-pass object in CUE

### PR DESCRIPTION
**Pull request by cnbailian**
feature #1685

### CODE REVIEW

**Review by wonderflow — APPROVED** [review]
It's pretty cool, let's add more tests for this case:

1. one or more e2e test case 
2. more unit test cases that covers the line

**Comment by cnbailian** [comment]
@leejanee  Hi, I wrote some unit tests, but I didn't get the errors covered [here](https://github.com/oam-dev/kubevela/blob/64d5bd3972c36bf156a8f777ee07d9953639459b/pkg/dsl/definition/template.go#L342) should I cancel getting the `err`?

**Comment by wonderflow** [comment]
@cnbailian much better, thanks

**Comment by cnbailian** [comment]
> @cnbailian much better, thanks

I haven’t added the E2E test yet...

**Comment by wonderflow** [comment]
@cnbailian  You can still add in another PR

**Pull request merged**
