### PR TITLE
Don't output all existing caps during vela workloads/traits

### LINKED ISSUE #522: [Feature] `vela workloads` and `vela traits` should list with silence if no changes
image

Only the part in red bracket is needed.

### PR DESCRIPTION
**Pull request by captainroy-hy**
to fix #522 
`vela system update` will output existing caps even no changes.
`vela workloads` and `vela traits` will not if no changes.

Demo screenshot:
image

Signed-off-by: roy wang <seiwy2010@gmail.com>

### CODE REVIEW

**Review by hongchaodeng — APPROVED** [review]
lgtm

**Comment by hongchaodeng** [comment]
defer to @wonderflow

**Review by wonderflow — APPROVED** [review]
LGTM， please remove the command `vela system update`

**Comment by captainroy-hy** [comment]
> LGTM， please remove the command `vela system update`

Got it. I will remove that command.

**Pull request merged**
