### PR TITLE
Added addons for other terraform provider

### PR DESCRIPTION
**Pull request by emanuelr93**
Solved this issue https://github.com/oam-dev/kubevela/issues/2457
Adding support for:

- AWS
- GCP
- VSPHERE
- EC

### CODE REVIEW

**Comment by chivalryq** [comment]
Here are some guide:

1. add template.yaml in `vela-templates/addons/`
2. run `go run ./vela-templates/gen_addons.go` to generate file
3. reinstall vela-core and try `vela addon enable terraform/provider-xxx` to test your addon.

Your job helps a lot!

**Comment by chivalryq** [comment]
Hi, do you have any problem with the guide? Files in `vela-templates/addons/` are needed, files in chart are generated. All files should be commited. :)

**Comment by chivalryq** [comment]
It would be better to add files in `vela-template` but if @emanuelr93 doesn't have more time, this is acceptable.

**Comment by emanuelr93** [comment]
Replaced with https://github.com/oam-dev/kubevela/pull/2672.

**Pull request closed without merging**
