### PR TITLE
Feat(workflow): add workflow CRD

### PR DESCRIPTION
**Pull request by FogDong**
**What this PR does / why we need it**:
add workflow CRD

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
/cc @leejanee

### CODE REVIEW

**Review by wonderflow — COMMENTED** [review]
let's hold this PR until v1.1 released

**Comment by hongchaodeng** [comment]
@leejanee 你先开一个 issue 写一下 TODO list? 然后这些 PR 都 link 一下那个 issue.

**Review by leejanee — COMMENTED** [review]
> @leejanee 你先开一个 issue 写一下 TODO list? 然后这些 PR 都 link 一下那个 issue.

ok

**Comment by leejanee** [comment]
#2096

**Review by hongchaodeng — APPROVED** [review]
lgtm

**Pull request merged**
