### PR TITLE
Fix sidebar and 404

### PR DESCRIPTION
**Pull request by resouer**
ref #1225 

We need to keep sidebar clean and neat.

What's missing here is more tutorials, I will expect they will come from `oam-dev/samples` repo.

### CODE REVIEW

**Comment by sunny0826** [comment]
I will refactor the kubevela site in multiple versions #1155 , like https://crossplane.io. So I need to keep the directory structure simple, easy to maintain and automate, so I need only two levels of directories like https://docs.fluxcd.io/projects/helm-operator/en/stable/ or https://crossplane.io/docs/v1.1/concepts/ so that there are only two levels of sidebars.

**Comment by resouer** [comment]
@sunny0826 OK, I will update the PR, thank you for heads up!

**Review by wonderflow — APPROVED** [review]
LGTM, feel free to merge when you're ready @resouer

**Comment by resouer** [comment]
PR updated sidebar to 2 layer.

**Pull request merged**
