### PR TITLE
Fix: fix workflow cli must have workflow in spec

### PR DESCRIPTION
**Pull request by FogDong**
Signed-off-by: FogDong <dongtianxin.tx@alibaba-inc.com>

### Description of your changes

fixes https://github.com/oam-dev/kubevela/issues/3431

Fix: fix workflow cli must have workflow in spec

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/oam-dev/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/oam-dev/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### Special notes for your reviewer

/cc @zzxwill

### CODE REVIEW

**Review by barnettZQG — APPROVED** [review]
lgtm

**Comment by wonderflow** [comment]
Can you clarify which case it won't work?

**Comment by wonderflow** [comment]
Does this PR fixes #3431  this case?

**Comment by zzxwill** [comment]
> Does this PR fixes #3431 this case?

Correct.

**Review by zzxwill — APPROVED** [review]

**Pull request merged**
