### PR TITLE
align to oam-k8s-runtime v0.3.0-rc1 and its CRD file

### PR DESCRIPTION
**Pull request by wonderflow**

### CODE REVIEW

**Comment by hongchaodeng** [comment]
Why duplicate crd in both oam-runtime and kubevela?

**Comment by wonderflow** [comment]
@hongchaodeng  We don't have a better way, do you have suggestions？

**Comment by hongchaodeng** [comment]
What are the CRDs used for?

**Comment by wonderflow** [comment]
@hongchaodeng  Install ， vela-core contains oam-k8s-runtime

**Review by hongchaodeng — APPROVED** [review]
I see.
LGTM

**Pull request merged**
