### PR TITLE
Feat(lang): The policy controller generate the OpenAPI schema  (#3683)

### LINKED ISSUE #3683: The policy controller does not generate the OpenAPI schema
**Describe the bug**

The policy controller does not generate the OpenAPI schema. By the way, all built-in policy does not have cue definition, so we should add cue definition to generate API schema.

**KubeVela Version**

1.3.1 

Relevance #3669

### PR DESCRIPTION
**Pull request by fengkang01**
### Description of your changes

Fixes #3683

* add policy controller generates the open API schema 
* add open API DetailDefinition support policy Definition

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/oam-dev/kubevela/blob/master/contribute/create-pull-request.md).
- [x] [Related Docs](https://github.com/oam-dev/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested
create policydefinition_controller_test.go file to testing.

1.When the PolicyDefinition is valid, but the namespace doesn't exist, should occur errors

2.When the PolicyDefinition is valid, should create a ConfigMap

3.When the PolicyDefinition is invalid, should report issues

### CODE REVIEW

**Comment by msftgits** [comment]
[CLA assistant check](https://cla.opensource.microsoft.com/oam-dev/kubevela?pullRequest=3703) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/oam-dev/kubevela?pullRequest=3703) before we can accept your contribution.<br/><br/>:x: fengkang01 [sign now](https://cla.opensource.microsoft.com/oam-dev/kubevela?pullRequest=3703)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/oam-dev/kubevela?pullRequest=3703) it.</sub>

**Review by barnettZQG — APPROVED** [review]
lgtm

**Comment by barnettZQG** [comment]
Thank your PR, please set you to want fixed issue and pass the DCO.

**Review by Somefive — APPROVED** [review]
LGTM

**Comment by wonderflow** [comment]
@fengkang01 Hi, please fix the CI

**Comment by fengkang01** [comment]
i will fix the CI at later tody

**Comment by fengkang01** [comment]
@wonderflow Hi,I have fixed CI

**Pull request merged**
