### PR TITLE
Fix: swagger error

### LINKED ISSUE #3372: go swagger generate client occur error by use swagger.json
**Describe the bug**

i want use go-swagger generate vela-apiserver client. but get below errors

```bash
docker run --rm -it --user $(shell id -u):$(shell id -g) -e GOPATH=$(shell go env GOPATH):/go -v $(shell pwd):$(shell pwd) -w $(shell pwd) quay.io/goswagger/swagger generate client -f https://raw.githubusercontent.com/oam-dev/kubevela/v1.2.4/docs/apidoc/swagger.json
2022/03/04 06:52:04 validating spec https://raw.githubusercontent.com/oam-dev/kubevela/v1.2.4/docs/apidoc/swagger.json
The swagger spec at "https://raw.githubusercontent.com/oam-dev/kubevela/v1.2.4/docs/apidoc/swagger.json" is invalid against swagger specification 2.0. see errors :
- "paths./api/v1/applications/{name}/envs/{envName}/recycle.post.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/envs/{envName}/recycle.post.responses.200.description in body is required
- "paths./api/v1/applications/{name}/envs/{envName}/recycle.post.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/envs/{envName}/recycle.post.responses.400.description in body is required
- "paths./api/v1/applications/{name}/envs/{envName}/status.get.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/envs/{envName}/status.get.responses.200.description in body is required
- "paths./api/v1/applications/{name}/envs/{envName}/status.get.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/envs/{envName}/status.get.responses.400.description in body is required
- "paths./api/v1/applications/{name}/template.post.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/template.post.responses.200.description in body is required
- "paths./api/v1/applications/{name}/template.post.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/template.post.responses.400.description in body is required
- "paths./api/v1/addons/{name}/enable.post.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/addons/{name}/enable.post.responses.200.description in body is required
- "paths./api/v1/addons/{name}/enable.post.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/addons/{name}/enable.post.responses.400.description in body is required
- "paths./api/v1/applications/{name}/components.get.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/components.get.responses.200.description in body is required
- "paths./api/v1/applications/{name}/components.get.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/components.get.responses.400.description in body is required
- "paths./api/v1/applications/{name}/components.post.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/components.post.responses.200.description in body is required
- "paths./api/v1/applications/{name}/components.post.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/components.post.responses.400.description in body is required
- "paths./api/v1/webhook/{token}.post.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/webhook/{token}.post.responses.200.description in body is required
- "paths./api/v1/webhook/{token}.post.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/webhook/{token}.post.responses.400.description in body is required
- "paths./api/v1/clusters/{clusterName}/namespaces.post.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/clusters/{clusterName}/namespaces.post.responses.200.description in body is required
- "paths./api/v1/clusters/{clusterName}/namespaces.post.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/clusters/{clusterName}/namespaces.post.responses.400.description in body is required
- "paths./api/v1/applications.get.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications.get.responses.200.description in body is required
- "paths./api/v1/applications.get.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications.get.responses.400.description in body is required
- "paths./api/v1/applications.post.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications.post.responses.200.description in body is required
- "paths./api/v1/applications.post.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications.post.responses.400.description in body is required
- "paths./api/v1/applications/{name}/workflows/{workflowName}/records/{record}/resume.get.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/workflows/{workflowName}/records/{record}/resume.get.responses.200.description in body is required
- "paths./api/v1/applications/{name}/workflows/{workflowName}/records/{record}/resume.get.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/workflows/{workflowName}/records/{record}/resume.get.responses.400.description in body is required
- "paths./api/v1/envs/{name}.put.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/envs/{name}.put.responses.200.description in body is required
- "paths./api/v1/envs/{name}.delete.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/envs/{name}.delete.responses.200.description in body is required
- "paths./api/v1/envs/{name}.delete.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/envs/{name}.delete.responses.400.description in body is required
- "paths./api/v1/applications/{name}/components/{compName}/traits/{traitType}.delete.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/components/{compName}/traits/{traitType}.delete.responses.200.description in body is required
- "paths./api/v1/applications/{name}/components/{compName}/traits/{traitType}.delete.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/components/{compName}/traits/{traitType}.delete.responses.400.description in body is required
- "paths./api/v1/applications/{name}/components/{compName}/traits/{traitType}.put.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/components/{compName}/traits/{traitType}.put.responses.200.description in body is required
- "paths./api/v1/applications/{name}/components/{compName}/traits/{traitType}.put.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/components/{compName}/traits/{traitType}.put.responses.400.description in body is required
- "paths./api/v1/clusters/cloud_clusters/{provider}.post.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/clusters/cloud_clusters/{provider}.post.responses.200.description in body is required
- "paths./api/v1/clusters/cloud_clusters/{provider}.post.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/clusters/cloud_clusters/{provider}.post.responses.400.description in body is required
- "paths./api/v1/clusters/cloud_clusters/{provider}.post.parameters" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/clusters/cloud_clusters/{provider}.post.parameters.type in body should be one of [string number boolean integer array]
- paths./api/v1/clusters/cloud_clusters/{provider}.post.parameters.in in body should be one of [header]
- "paths./api/v1/applications/{name}.get.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}.get.responses.200.description in body is required
- "paths./api/v1/applications/{name}.get.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}.get.responses.400.description in body is required
- "paths./api/v1/applications/{name}.put.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}.put.responses.200.description in body is required
- "paths./api/v1/applications/{name}.put.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}.put.responses.400.description in body is required
- "paths./api/v1/applications/{name}.delete.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}.delete.responses.200.description in body is required
- "paths./api/v1/applications/{name}.delete.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}.delete.responses.400.description in body is required
- "paths./api/v1/applications/{name}/policies.get.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/policies.get.responses.200.description in body is required
- "paths./api/v1/applications/{name}/policies.get.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/policies.get.responses.400.description in body is required
- "paths./api/v1/applications/{name}/policies.post.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/policies.post.responses.200.description in body is required
- "paths./api/v1/applications/{name}/policies.post.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/policies.post.responses.400.description in body is required
- "paths./api/v1/applications/{name}/revisions.get.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/revisions.get.responses.200.description in body is required
- "paths./api/v1/applications/{name}/revisions.get.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/revisions.get.responses.400.description in body is required
- "paths./api/v1/applications/{name}/statistics.get.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/statistics.get.responses.200.description in body is required
- "paths./api/v1/applications/{name}/statistics.get.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/statistics.get.responses.400.description in body is required
- "paths./api/v1/clusters/cloud_clusters/{provider}/connect.post.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/clusters/cloud_clusters/{provider}/connect.post.responses.200.description in body is required
- "paths./api/v1/clusters/cloud_clusters/{provider}/connect.post.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/clusters/cloud_clusters/{provider}/connect.post.responses.400.description in body is required
- "paths./api/v1/clusters/cloud_clusters/{provider}/creation.get.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/clusters/cloud_clusters/{provider}/creation.get.responses.200.description in body is required
- "paths./api/v1/clusters/cloud_clusters/{provider}/creation.get.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/clusters/cloud_clusters/{provider}/creation.get.responses.400.description in body is required
- "paths./api/v1/addons/{name}/status.get.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/addons/{name}/status.get.responses.200.description in body is required
- "paths./api/v1/addons/{name}/status.get.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/addons/{name}/status.get.responses.400.description in body is required
- "paths./api/v1/applications/payload_types.get.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/payload_types.get.responses.200.description in body is required
- "paths./api/v1/applications/payload_types.get.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/payload_types.get.responses.400.description in body is required
- "paths./api/v1/envs.get.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/envs.get.responses.200.description in body is required
- "paths./api/v1/envs.post.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/envs.post.responses.200.description in body is required
- "paths./api/v1/query.get.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/query.get.responses.200.description in body is required
- "paths./api/v1/query.get.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/query.get.responses.400.description in body is required
- "paths./api/v1/addon_registries/{name}.delete.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/addon_registries/{name}.delete.responses.200.description in body is required
- "paths./api/v1/addon_registries/{name}.delete.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/addon_registries/{name}.delete.responses.400.description in body is required
- "paths./api/v1/addon_registries/{name}.put.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/addon_registries/{name}.put.responses.200.description in body is required
- "paths./api/v1/addon_registries/{name}.put.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/addon_registries/{name}.put.responses.400.description in body is required
- "paths./api/v1/applications/{name}/records.get.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/records.get.responses.200.description in body is required
- "paths./api/v1/applications/{name}/records.get.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/records.get.responses.400.description in body is required
- "paths./api/v1/clusters/cloud_clusters/{provider}/creation/{cloudClusterName}.get.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/clusters/cloud_clusters/{provider}/creation/{cloudClusterName}.get.responses.200.description in body is required
- "paths./api/v1/clusters/cloud_clusters/{provider}/creation/{cloudClusterName}.get.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/clusters/cloud_clusters/{provider}/creation/{cloudClusterName}.get.responses.400.description in body is required
- "paths./api/v1/clusters/cloud_clusters/{provider}/creation/{cloudClusterName}.delete.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/clusters/cloud_clusters/{provider}/creation/{cloudClusterName}.delete.responses.200.description in body is required
- "paths./api/v1/clusters/cloud_clusters/{provider}/creation/{cloudClusterName}.delete.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/clusters/cloud_clusters/{provider}/creation/{cloudClusterName}.delete.responses.400.description in body is required
- "paths./api/v1/applications/{name}/policies/{policyName}.get.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/policies/{policyName}.get.responses.200.description in body is required
- "paths./api/v1/applications/{name}/policies/{policyName}.get.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/policies/{policyName}.get.responses.400.description in body is required
- "paths./api/v1/applications/{name}/policies/{policyName}.put.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/policies/{policyName}.put.responses.200.description in body is required
- "paths./api/v1/applications/{name}/policies/{policyName}.put.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/policies/{policyName}.put.responses.400.description in body is required
- "paths./api/v1/applications/{name}/policies/{policyName}.delete.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/policies/{policyName}.delete.responses.200.description in body is required
- "paths./api/v1/applications/{name}/policies/{policyName}.delete.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/policies/{policyName}.delete.responses.400.description in body is required
- "paths./api/v1/clusters.get.parameters" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/clusters.get.parameters.in in body should be one of [header]
- paths./api/v1/clusters.get.parameters.type in body should be one of [string number boolean integer array]
- "paths./api/v1/clusters.get.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/clusters.get.responses.400.description in body is required
- "paths./api/v1/clusters.post.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/clusters.post.responses.200.description in body is required
- "paths./api/v1/clusters.post.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/clusters.post.responses.400.description in body is required
- "paths./api/v1/enabled_addon.get.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/enabled_addon.get.responses.200.description in body is required
- "paths./api/v1/enabled_addon.get.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/enabled_addon.get.responses.400.description in body is required
- "paths./api/v1/applications/{name}/revisions/{revision}.get.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/revisions/{revision}.get.responses.200.description in body is required
- "paths./api/v1/applications/{name}/revisions/{revision}.get.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/revisions/{revision}.get.responses.400.description in body is required
- "paths./api/v1/applications/{name}/envs.get.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/envs.get.responses.200.description in body is required
- "paths./api/v1/applications/{name}/envs.get.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/envs.get.responses.400.description in body is required
- "paths./api/v1/applications/{name}/envs.post.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/envs.post.responses.400.description in body is required
- "paths./api/v1/applications/{name}/envs.post.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/envs.post.responses.200.description in body is required
- "paths./api/v1/projects.post.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/projects.post.responses.200.description in body is required
- "paths./api/v1/projects.get.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/projects.get.responses.200.description in body is required
- "paths./v1/namespaces/{namespace}/applications/{appname}.get.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./v1/namespaces/{namespace}/applications/{appname}.get.responses.200.description in body is required
- "paths./api/v1/applications/{name}/components/{compName}.put.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/components/{compName}.put.responses.200.description in body is required
- "paths./api/v1/applications/{name}/components/{compName}.put.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/components/{compName}.put.responses.400.description in body is required
- "paths./api/v1/applications/{name}/components/{compName}.get.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/components/{compName}.get.responses.200.description in body is required
- "paths./api/v1/applications/{name}/components/{compName}.get.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/components/{compName}.get.responses.400.description in body is required
- "paths./api/v1/applications/{name}/components/{compName}/traits.post.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/components/{compName}/traits.post.responses.200.description in body is required
- "paths./api/v1/applications/{name}/components/{compName}/traits.post.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/components/{compName}/traits.post.responses.400.description in body is required
- "paths./api/v1/applications/{name}/envs/{envName}.delete.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/envs/{envName}.delete.responses.200.description in body is required
- "paths./api/v1/applications/{name}/envs/{envName}.delete.responses.404" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/envs/{envName}.delete.responses.404.description in body is required
- "paths./api/v1/applications/{name}/envs/{envName}.put.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/envs/{envName}.put.responses.200.description in body is required
- "paths./api/v1/applications/{name}/envs/{envName}.put.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/envs/{envName}.put.responses.400.description in body is required
- "paths./api/v1/addon_registries.get.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/addon_registries.get.responses.200.description in body is required
- "paths./api/v1/addon_registries.get.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/addon_registries.get.responses.400.description in body is required
- "paths./api/v1/addon_registries.post.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/addon_registries.post.responses.200.description in body is required
- "paths./api/v1/addon_registries.post.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/addon_registries.post.responses.400.description in body is required
- "paths./api/v1/addons/{name}/disable.post.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/addons/{name}/disable.post.responses.200.description in body is required
- "paths./api/v1/addons/{name}/disable.post.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/addons/{name}/disable.post.responses.400.description in body is required
- "paths./api/v1/applications/{name}/workflows/{workflowName}/records/{record}/rollback.get.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/workflows/{workflowName}/records/{record}/rollback.get.responses.200.description in body is required
- "paths./api/v1/applications/{name}/workflows/{workflowName}/records/{record}/rollback.get.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/workflows/{workflowName}/records/{record}/rollback.get.responses.400.description in body is required
- "paths./api/v1/applications/{name}/deploy.post.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/deploy.post.responses.200.description in body is required
- "paths./api/v1/applications/{name}/deploy.post.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/deploy.post.responses.400.description in body is required
- "paths./api/v1/applications/{name}/triggers.get.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/triggers.get.responses.400.description in body is required
- "paths./api/v1/applications/{name}/triggers.get.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/triggers.get.responses.200.description in body is required
- "paths./api/v1/applications/{name}/triggers.post.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/triggers.post.responses.200.description in body is required
- "paths./api/v1/applications/{name}/triggers.post.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/triggers.post.responses.400.description in body is required
- "paths./api/v1/applications/{name}/triggers/{token}.delete.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/triggers/{token}.delete.responses.200.description in body is required
- "paths./api/v1/applications/{name}/triggers/{token}.delete.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/triggers/{token}.delete.responses.400.description in body is required
- "paths./api/v1/addons/{name}.get.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/addons/{name}.get.responses.400.description in body is required
- "paths./api/v1/addons/{name}.get.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/addons/{name}.get.responses.200.description in body is required
- "paths./api/v1/clusters/cloud_clusters/{provider}/create.post.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/clusters/cloud_clusters/{provider}/create.post.responses.200.description in body is required
- "paths./api/v1/clusters/cloud_clusters/{provider}/create.post.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/clusters/cloud_clusters/{provider}/create.post.responses.400.description in body is required
- "paths./api/v1/applications/{name}/workflows/{workflowName}/records/{record}/terminate.get.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/workflows/{workflowName}/records/{record}/terminate.get.responses.400.description in body is required
- "paths./api/v1/applications/{name}/workflows/{workflowName}/records/{record}/terminate.get.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/applications/{name}/workflows/{workflowName}/records/{record}/terminate.get.responses.200.description in body is required
- "paths./api/v1/clusters/{clusterName}.delete.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/clusters/{clusterName}.delete.responses.200.description in body is required
- "paths./api/v1/clusters/{clusterName}.delete.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/clusters/{clusterName}.delete.responses.400.description in body is required
- "paths./api/v1/clusters/{clusterName}.get.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/clusters/{clusterName}.get.responses.200.description in body is required
- "paths./api/v1/clusters/{clusterName}.get.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/clusters/{clusterName}.get.responses.400.description in body is required
- "paths./api/v1/clusters/{clusterName}.put.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/clusters/{clusterName}.put.responses.200.description in body is required
- "paths./api/v1/clusters/{clusterName}.put.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/clusters/{clusterName}.put.responses.400.description in body is required
- "paths./api/v1/policy_definitions.get.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/policy_definitions.get.responses.200.description in body is required
- "paths./api/v1/addons.get.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/addons.get.responses.200.description in body is required
- "paths./api/v1/addons.get.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/addons.get.responses.400.description in body is required
- "paths./api/v1/addons/{name}/update.put.responses.400" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/addons/{name}/update.put.responses.400.description in body is required
- "paths./api/v1/addons/{name}/update.put.responses.200" must validate one and only one schema (oneOf). Found none valid
- paths./api/v1/addons/{name}/update.put.responses.200.description in body is required

make: *** [client] Error 1
```

seem swagger file does not meet the standard.

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**

### PR DESCRIPTION
**Pull request by zhiyuone**
Signed-off-by: Zhiyu Wang <zhiyuwang.newbis@gmail.com>

### Description of your changes

Fixes #3372

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/oam-dev/kubevela/blob/master/contribute/create-pull-request.md).
- [x] [Related Docs](https://github.com/oam-dev/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Comment by msftgits** [comment]
[CLA assistant check](https://cla.opensource.microsoft.com/oam-dev/kubevela?pullRequest=3373) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/oam-dev/kubevela?pullRequest=3373) before we can accept your contribution.<br/><br/>:x: zhiyuone [sign now](https://cla.opensource.microsoft.com/oam-dev/kubevela?pullRequest=3373)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/oam-dev/kubevela?pullRequest=3373) it.</sub>

**Comment by barnettZQG** [comment]
@zhiyuone Good job! Please update the swagger config by `make build-swagger`

**Review by wonderflow — APPROVED** [review]
ping @barnettZQG

**Review by barnettZQG — APPROVED** [review]
LGTM

**Pull request merged**
