### PR TITLE
check yarn docusaurus

### PR DESCRIPTION
**Pull request by charles-woshicai**
fixes: https://github.com/oam-dev/kubevela/issues/1518

### CODE REVIEW

**Comment by charles-woshicai** [comment]
@wonderflow I haven't reproduced the issue in my local environment, the shell would exit if command is failed.

Just check whether the directory is exist and not empty.

**Review by wonderflow — APPROVED** [review]
cool

**Comment by wonderflow** [comment]
#1609 is  fixing the CI, please rebase after that PR merged

**Comment by wonderflow** [comment]
@charles-woshicai  please rebase

**Pull request merged**
