### PR TITLE
Feat: add log provider

### LINKED ISSUE #3682: [Feature] add the print provider function for cue engine
**Is your feature request related to a problem? Please describe.**

When we coding the cue script, want to know the params values for debugging. the cue script is used on VelaQL, addon, workflow, and other features in the KubeVela.

**Describe the solution you'd like**

```
...
resources: ql.#ListResourcesInApp & {
      app: {
          name:      parameter.appName
          namespace: parameter.appNs
          filter: {
              if parameter.cluster != _|_ {
                  cluster: parameter.cluster
              }
              if parameter.clusterNs != _|_ {
                  clusterNamespace: parameter.clusterNs
              }
              if parameter.name != _|_ {
                  components: [parameter.name]
              }
          }
      }
  }
debugInfo: ql.#Print & resources
...
```
I hope the resources will print in the runtime log.

### PR DESCRIPTION
**Pull request by FogDong**
Signed-off-by: FogDong <dongtianxin.tx@alibaba-inc.com>

### Description of your changes

Fixes #3682
add log provider

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/oam-dev/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/oam-dev/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### Special notes for your reviewer

/cc @barnettZQG

### CODE REVIEW

**Comment by barnettZQG** [comment]
@FogDong Looking forward to giving a use case.

**Comment by FogDong** [comment]
> @FogDong Looking forward to giving a use case.

Will add to doc (built-in cue actions) after PR is merged.

**Review by barnettZQG — APPROVED** [review]
LGTM

**Review by leejanee — APPROVED** [review]
LGTM

**Pull request merged**
