### PR TITLE
refactor: move from io/ioutil to io and os package

### PR DESCRIPTION
**Pull request by Juneezee**
**What this PR does / why we need it**:
The `io/ioutil` package has been deprecated in Go 1.16 (See https://golang.org/doc/go1.16#ioutil). This PR replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages. No breaking changes.

**Which issue(s) this PR fixes**:
N/A

**Special notes for your reviewer**:
N/A

### CODE REVIEW

**Review by wonderflow — APPROVED** [review]
good job，thanks

**Review by zzxwill — APPROVED** [review]
/lgtm

**Review by hongchaodeng — APPROVED** [review]

**Comment by hongchaodeng** [comment]
@Somefive @leejanee @wangyikewxgm 
Github would need your approval to merge this PR

**Review by Somefive — APPROVED** [review]
lgtm

**Review by wangyikewxgm — APPROVED** [review]
LGTM

**Review by leejanee — APPROVED** [review]
lgtm

**Pull request merged**
