### PR TITLE
Feat: support install and uninstall vela core

### PR DESCRIPTION
**Pull request by barnettZQG**
Signed-off-by: barnettZQG <barnett.zqg@gmail.com>

### Description of your changes

To further reduce the user installation threshold, The vela CLI add the following command:

* `vela install`: Installs or Upgrades Kubevela control plane on a Kubernetes cluster. 

```
vela install
vela install --version v1.2.2
vela install --version v1.2.2 --set resources.limits.memory=2Gi
vela install -f ./vela-core-v1.2.2.tgz  // offline install
```
* `vela uninstall`:  Uninstalls KubeVela control plane from a Kubernetes cluster.

* `vela version list`: List all available and newer versions.
```
vela version list -a  // List all available versions.
```
* `vela ls -A`: List all applications in all namespaces.

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/oam-dev/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/oam-dev/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Review by Somefive — APPROVED** [review]
Generally LGTM. Minor issues might be considered for later work.
1. Support version >=1.19, <=1.21 is a bit restrictive. As our CI uses 1.18, we should at least keep compatibility with k8s 1.18 in my opinion. 1.22 might be more difficult as we have not been doing tests on 1.22 but in long term, it should be supported.
2. The functionality of `vela install` is fancy but the command name might be a bit ambiguous. The version of CLI and the version of KubeVela Controller might need to be distinguished somewhere. Similar to `vela version list`.

**Review by wonderflow — COMMENTED** [review]
please change the e2e to use the `vela install` to install the chart instead of helm install

**Comment by zzxwill** [comment]
The subcommand is cool. Do we need `vela upgrade --install`? I used `helm upgrade --install ` a lot for helm chart upgration. And community users asked many questions about vela core upgration.

**Comment by wonderflow** [comment]
> The subcommand is cool. Do we need `vela upgrade --install`? I used `helm upgrade --install ` a lot for helm chart upgration. And community users asked many questions about vela core upgration.

good idea, so we just need `vela upgrade`, no need for `vela install`

**Review by wonderflow — APPROVED** [review]

**Comment by wonderflow** [comment]
CRD should be upgraded first before the chart upgrade.

**Pull request merged**
