### PR TITLE
Build: bump to use go1.17 and setup-go v2

### PR DESCRIPTION
**Pull request by chenrui333**
**What this PR does / why we need it**: Ensure the dependencies up to date

### CODE REVIEW

**Comment by hongchaodeng** [comment]
Since go 1.17 is released recently, I would suggest to wait a couple more minor version releases before bumping it.

**Comment by wonderflow** [comment]
Hi, I think we can switch to Go v1.17 now, would you like to help? @chenrui333

**Comment by chenrui333** [comment]
Sure, I will do it tomorrow. :)

**Comment by wonderflow** [comment]
we have already bumped the GO version, feel free to send a new PR if there's anything left. Closing by now.

**Pull request closed without merging**
