### PR TITLE
Fix: Optimize error msg of addon enable/upgrade local path

### LINKED ISSUE #3183: When a local addon's path is not right, the error message does not correctly indicate the issue
**Describe the bug**

When a local addon's path is not right, the error message does not correctly indicate the issue

```
➜  catalog git:(generate-terraform-addon) ✗ vela addon enable ./sfsfjsdlfjsdlfjsdlfjsd
Error: addon: ./sfsfjsdlfjsdlfjsdlfjsd not found in registries
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**

### PR DESCRIPTION
**Pull request by JooKS-me**
Signed-off-by: zhukunshuai <jookunshuai@gmail.com>

### Description of your changes

Fixes #3183 

I have:

- [X] Read and followed KubeVela's [contribution process](https://github.com/oam-dev/kubevela/blob/master/contribute/create-pull-request.md).
- [X] [Related Docs](https://github.com/oam-dev/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [X] Run `make reviewable` to ensure this PR is ready for review.
- [X] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Comment by zzxwill** [comment]
Great job! Would you please add some unit-tests to cover the cases listed by @wonderflow https://github.com/oam-dev/kubevela/issues/3183#issuecomment-1033682064

**Comment by JooKS-me** [comment]
> Great job! Would you please add some unit-tests to cover the cases listed by @wonderflow [#3183 (comment)](https://github.com/oam-dev/kubevela/issues/3183#issuecomment-1033682064)?

OK :)

**Review by wonderflow — APPROVED** [review]

**Comment by JooKS-me** [comment]
Hi here, is there anything else that needs to be changed?

**Review by Somefive — APPROVED** [review]
LGTM

**Pull request merged**
