### PR TITLE
Feat(workflow): add depends on in workflow

### LINKED ISSUE #2370: [Feature] Support dependsOn in Component deployment DAG
Such as: 

image

Or

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: wordpress-with-mysql
  namespace: default
spec:
  components:
    - name: mysql
      type: helm
      properties:
        repoType: helm
        url: https://charts.bitnami.com/bitnami
        chart: mysql
        version: "8.8.2"
    - name: wordpress
      type: helm
      inputs:
        # dependsOn the mysql component to be ready
        - dependsOn: mysql
      properties:
        repoType: helm
        url: https://charts.bitnami.com/bitnami
        chart: wordpress
        version: "12.0.3"
```

> 希望能够在Application里直观的看到到底哪些component存在依赖关系. 因为依赖关系是个比较通用的能力，执行过程都是DAG工作流，就看是否可以更友好一点

### PR DESCRIPTION
**Pull request by FogDong**
**What this PR does / why we need it**:
add depends on in workflow

**Which issue(s) this PR fixes**:

Fixes #2370

**Special notes for your reviewer**:

### CODE REVIEW

**Review by hongchaodeng — APPROVED** [review]
I think the code LGTM.
But the code does not implement or fix https://github.com/oam-dev/kubevela/issues/2370 ...
The problem is that it will report "ready" once the component is applied.. We still need to implement StartupProbe for that.

**Comment by hongchaodeng** [comment]
Maybe this is just the first step to fix #2370 . Please change the top comment to reflect that.

**Comment by hongchaodeng** [comment]
Maybe this is just the first step to fix #2370 . Please change the top comment to reflect that.

**Comment by FogDong** [comment]
> I think the code LGTM. But the code does not implement or fix #2370 ... The problem is that it will report "ready" once the component is applied.. We still need to implement StartupProbe for that.

It will report `ready` when the workflow step phase is `succeeded`.
Now the workflow step phase is based on `isHealth`, we can change it to  StartupProbe later.

**Review by wonderflow — APPROVED** [review]

**Review by leejanee — APPROVED** [review]

**Pull request merged**
