### PR TITLE
Fix(addon): rename clonset-service to clonset

### PR DESCRIPTION
**Pull request by wangyikewxgm**
**What this PR does / why we need it**:
rename clonset-service to clonset

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by hongchaodeng — APPROVED** [review]
lgtm

**Review by wonderflow — COMMENTED** [review]
please also fix the related docs

**Review by Somefive — APPROVED** [review]
LGTM

**Comment by wangyikewxgm** [comment]
> please also fix the related docs

Have fixed by https://github.com/oam-dev/kubevela.io/pull/225

**Pull request merged**
