### PR TITLE
Refactor: refactor Helm chart with unnecessary 'systemDefinitionNames` value

### PR DESCRIPTION
**Pull request by nashtsai**
### Description of your changes

Refactor Helm chart with unnecessary 'systemDefinitionNames' value

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/oam-dev/kubevela/blob/master/contribute/create-pull-request.md).
- [x] [Related Docs](https://github.com/oam-dev/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

```
cd charts/vele-core/
helm upgrade --install my-vela-release ./   -n <ns> --create-namespace
# expected helm upgrade/install with no error reported
```

### Special notes for your reviewer

Nil

### CODE REVIEW

**Review by wonderflow — COMMENTED** [review]
we should tolerance the need that users want to use different namespace for controller installation and Definitions.

**Comment by nashtsai** [comment]
> we should tolerance the need that users want to use different namespace for controller installation and Definitions.

resubmitted with defaulter handling, will use built-in `.Release.Namespace` var if `.Values.systemDefinitionNamespace` is unspecified.

**Comment by nashtsai** [comment]
> we should tolerance the need that users want to use different namespace for controller installation and Definitions.

resubmitted with defaulter handling, if `.Values.systemDefinitionNamespace` is unspecifed then it will use

**Review by wonderflow — APPROVED** [review]
nice job

**Comment by wonderflow** [comment]
You should change the definition with this line https://github.com/oam-dev/kubevela/blob/master/references/cli/def.go#L686
And use `make reviewable` to generate the files automatically.

**Comment by msftgits** [comment]
[CLA assistant check](https://cla.opensource.microsoft.com/oam-dev/kubevela?pullRequest=3267) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/oam-dev/kubevela?pullRequest=3267) before we can accept your contribution.<br/><br/>:x: nashtsai [sign now](https://cla.opensource.microsoft.com/oam-dev/kubevela?pullRequest=3267)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/oam-dev/kubevela?pullRequest=3267) it.</sub>

**Pull request merged**
