### PR TITLE
Fix: use Terraform provider name as application in CLI

### PR DESCRIPTION
**Pull request by zzxwill**
In CLI, use Terraform provider name as application name when
create a Provider. Also display there providers in VelaUX.
1). manually created a Terraform Provider object, like https://github.com/oam-dev/terraform-controller/blob/master/getting-started.md#aws
2). by enabling a Terraform provider addon in version older than v1.3.0
3). by create a Terraform provider via `vela provider add`
4). by VelaUX

Signed-off-by: Zheng Xi Zhou <zzxwill@gmail.com>

### Description of your changes

Fixes #

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/oam-dev/kubevela/blob/master/contribute/create-pull-request.md).
- [x] [Related Docs](https://github.com/oam-dev/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Comment by Somefive** [comment]
I'm afraid `vela provider` is a bit confusing. We also have `provider` concept in workflow. So it might be better to use an alternative name like `vela cloud-provider`?

**Comment by zzxwill** [comment]
> I'm afraid `vela provider` is a bit confusing. We also have `provider` concept in workflow. So it might be better to use an alternative name like `vela cloud-provider`?

With our offline discussion, we may use `vela config provider` in the future. But currently, config is just a concept of KubeVela. So let's keep it as it is right now.

**Review by Somefive — APPROVED** [review]
Generally LGTM

**Review by yangsoon — APPROVED** [review]

**Review by wonderflow — APPROVED** [review]

**Comment by zzxwill** [comment]
> Backport failed for `release-1.3`, because it was unable to cherry-pick the commit(s).
> 
> Please cherry-pick the changes locally.
> 
> ```shell
> git fetch origin release-1.3
> git worktree add -d .worktree/backport-3742-to-release-1.3 origin/release-1.3
> cd .worktree/backport-3742-to-release-1.3
> git checkout -b backport-3742-to-release-1.3
> ancref=$(git merge-base 2d28fb35ebfff1bbdff536a211140380cefab055 3518b4b62c6dbf86a500683ef994601e9a660cf1)
> git cherry-pick -x $ancref..3518b4b62c6dbf86a500683ef994601e9a660cf1
> ```

Done with https://github.com/oam-dev/kubevela/pull/3756.

**Pull request merged**
