### PR TITLE
chore: use buildkit for building docker-images

### LINKED ISSUE #416: Use buildkit to build docker images
Currently the code calls local `docker` command. We should consider using buildkit: https://github.com/moby/buildkit

### PR DESCRIPTION
**Pull request by kushthedude**
Signed-off-by: kushthedude <kushthedude@gmail.com>
fixes #416

### CODE REVIEW

**Comment by kushthedude** [comment]
Hi team, I am not sure if e2e-tests failure is due to the changes in the PR as I added a flag to use buildit while building the docker images?

**Comment by hongchaodeng** [comment]
Hi @kushthedude. Thanks for your contribution.
I think the issue  #416 means we want to use the buildkit go library to build the image instead of relying on the docker command. Not adding `DOCKER_BUILDKIT` flag.

**Comment by kushthedude** [comment]
Hi @hongchaodeng , can you please review it now? I have replaced `docker build` with `buildctl`, also should we then replace `docker push` with `buildctl build & push=true`?

**Comment by wonderflow** [comment]
Thanks for your contributions, we found this issue can't be resolved by now #416 

Closing

**Pull request closed without merging**
